[package]
name = "webpack-tree"
version = "0.1.0"
authors = ["Dennis Oelkers <dennis@graylog.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "1.8"
